/*
 * Netmaker
 *
 * # API Usage  Most actions that can be performed via API can be performed via UI. We recommend managing your networks using the official netmaker-ui project. However, Netmaker can also be run without the UI, and all functions can be achieved via API calls. If your use case requires using Netmaker without the UI or you need to do some troubleshooting/advanced configuration, using the API directly may help.  # Authentication  API calls must be authenticated via a header of the format -H “Authorization: Bearer <YOUR_SECRET_KEY>” There are two methods to obtain YOUR_SECRET_KEY: 1. Using the masterkey. By default, this value is “secret key,” but you should change this on your instance and keep it secure. This value can be set via env var at startup or in a config file (config/environments/< env >.yaml). See the [Netmaker](https://docs.netmaker.org/index.html) documentation for more details. 2. Using a JWT received for a node. This can be retrieved by calling the /api/nodes/<network>/authenticate endpoint, as documented below.
 *
 * API version: 0.24.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// Host - represents a host on the network
type Host struct {
	Autoupdate bool `json:"autoupdate,omitempty"`
	Daemoninstalled bool `json:"daemoninstalled,omitempty"`
	Debug bool `json:"debug,omitempty"`
	Defaultinterface string `json:"defaultinterface,omitempty"`
	Endpointip string `json:"endpointip,omitempty"`
	Endpointipv6 string `json:"endpointipv6,omitempty"`
	Firewallinuse string `json:"firewallinuse,omitempty"`
	Hostpass string `json:"hostpass,omitempty"`
	Id string `json:"id,omitempty"`
	Interface_ string `json:"interface,omitempty"`
	Interfaces []Iface `json:"interfaces,omitempty"`
	Ipforwarding bool `json:"ipforwarding,omitempty"`
	Isdefault bool `json:"isdefault,omitempty"`
	Isdocker bool `json:"isdocker,omitempty"`
	Isk8s bool `json:"isk8s,omitempty"`
	Isstatic bool `json:"isstatic,omitempty"`
	Listenport int64 `json:"listenport,omitempty"`
	Macaddress *HardwareAddr `json:"macaddress,omitempty"`
	Mtu int64 `json:"mtu,omitempty"`
	Name string `json:"name,omitempty"`
	NatType string `json:"nat_type,omitempty"`
	Nodes []string `json:"nodes,omitempty"`
	Os string `json:"os,omitempty"`
	Persistentkeepalive *Duration `json:"persistentkeepalive,omitempty"`
	Publickey *Key `json:"publickey,omitempty"`
	Traffickeypublic []int32 `json:"traffickeypublic,omitempty"`
	TurnEndpoint string `json:"turn_endpoint,omitempty"`
	Verbosity int64 `json:"verbosity,omitempty"`
	Version string `json:"version,omitempty"`
	WgPublicListenPort int64 `json:"wg_public_listen_port,omitempty"`
}
