name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
      
      - name: Build for multiple platforms
        run: |
          GOOS=linux GOARCH=amd64 go build -o netmaker-sync-linux-amd64
          GOOS=darwin GOARCH=amd64 go build -o netmaker-sync-darwin-amd64
          GOOS=windows GOARCH=amd64 go build -o netmaker-sync-windows-amd64.exe
      
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            netmaker-sync-linux-amd64
            netmaker-sync-darwin-amd64
            netmaker-sync-windows-amd64.exe
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}